quotes = [
    ("Imagination is more important than knowledge", "Albert Einstein"),
    ("If Barbie is so popular, why do you have to buy her friends?", "Steven Wright"),
    ("A verbal contract is not worth the paper it's written on.", "Samuel Goldwyn"),
    ("Facts are stupid things.", "Ronald Reagan, Former U.S. President"),
    ("Solutions are not the answer.", "Richard Nixon, former U.S. President"),
    ("A dentist at work in his vocation always looks down in the mouth.", "George D. Prentice"),
    ("You don't have to brush your teeth - just the ones you want to keep.", "Unknown"),
    ("The man with a toothache thinks everyone happy whose teeth are sound.", "George Bernard Shaw"),
    ("We do have a zeal for laughter in most situations, give or take a dentist.", "Joseph Heller"),
    ("Even pearls are dark before the whiteness of his teeth.", "William R. Alger"),
    ("If a patient cannot clean his teeth, no dentist can clean them for him.", "Martin H. Fischer"),
    ("A man loses his illusions first, his teeth second, and his follies last.", "Helen Rowland"),
    ("The tongue is ever turning to the aching tooth.", "Thomas Fuller"),
    ("Teeth extracted by the latest methodists.", "Hong Kong dental advertisement"),
    ("Many people would sooner die than think; in fact, they do so.", "Bertrand Russell"),
    ("The clue train passed his station without stopping.", "John Simmons / outlaw programmer"),
    ("Plan to throw one away, you will anyhow.", "Fred Brooks"),
    ("C++ tries to guard against Murphy, not Machiavelli.", "Damian Conway"),
    ("Style distinguishes excellence from accomplishment.", "James Coplien"),
    ("Learning is not compulsory. Neither is survival.", "W. Edwards Deming"),
    ("To iterate is human, to recurse divine.", "L. Peter Deutsch"),
    ("Simplicity is prerequisite for reliability", "Edsger W. Dijkstra"),
    ("Make everything as simple as possible, but not simpler.", "Albert Einstein"),
    ("The inside of a computer is as dumb as hell but it goes like mad!", "Richard Feynman"),
    ("Simplicity carried to the extreme becomes elegance.", "Jon Franklin"),
    ("An API that isn't comprehensible isn't usable.", "James Gosling"),
    ("Never attribute to malice that which is adequately explained by stupidity.", "Hanlon's razor"),
    ("The unavoidable price of reliability is simplicity.", "C.A.R. Hoare"),
    ("Before software can be reusable it first has to be usable.", "Ralph Johnson"),
    ("First, solve the problem. Then, write the code.", "John Johnson"),
    ("We are faced with an insurmountable opportunity.", "W. Kelley"),
    ("Computers are good at following instructions, but not at reading your mind.", "Donald Knuth"),
    ("You're bound to be unhappy if you optimize everything.", "Donald Knuth"),
    ("Without stress nothing would move.", "Bill Langley"),
    ("Incompetents invariably make trouble for people other than themselves.", "Larry McMurtry"),
    ("Haste is of the devil. Slowness is of God.", "H L Mencken"),
    ("Incorrect documentation is often worse than no documentation.", "Bertrand Meyer"),
    ("Any fool can use a computer. Many do.", "Ted Nelson"),
    ("The truth does not change according to our ability to stomach it.", "Flannery O'Connor"),
    ("Elegance is not optional", "Richard O'Keefe"),
    ("Copy and paste is a design error", "David Parnas"),
    ("There are two ways to write error-free programs; only the third works.", "Alan J. Perlis"),
    ("Computers are useless. They can only give you answers.", "Pablo Picasso"),
    ("UNIX is simple. It just takes a genius to understand its simplicity.", "Dennis Ritchie"),
    ("Even if you're on the right track, you'll get run over if you just sit there.", "Will Rogers"),
    ("Those who cannot remember the past are condemned to repeat it.", "George Santayana"),
    ("If you lie to the compiler, it will get its revenge.", "Henry Spencer"),
    ("A notation is important for what it leaves out.", "Joseph Stoy"),
    ("A multithreaded file system is only a performance hack.", "Prof. Andrew S. Tanenbaum"),
    ("There are only two industries that refer to their customers as 'users'.", "Edward Tufte"),
    ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
    ("The best is the enemy of the good.", "Voltaire"),
    ("If you plan to throw one away, you will throw away two.", "Craig Zerouni"),
    ("I don't care if it works on your machine! We are not shipping your machine!", "Vidiu Platon"),
    ("Stories of imagination tend to upset those without one.", "Terry Pratchett"),
    ("Time is a drug. Too much of it kills you.", "Terry Pratchett (Small Gods) "),
    ("In the beginning there was nothing, which exploded.", "Terry Pratchett (Lords and Ladies) "),
    ("Real stupidity beats artificial intelligence every time.", "Terry Pratchett (Hogfather) "),
    ("Five exclamation marks, the sure sign of an insane mind.", "Terry Pratchett (Reaper Man) "),
    ("If you have enough book space, I don't want to talk to you.", "Terry Pratchett"),
    ("I'd rather be a climbing ape than a falling angel.", "Terry Pratchett"),
    ("This isn't life in the fast lane, it's life in the oncoming traffic.", "Terry Pratchett"),
    ("We who think we are about to die will laugh at anything.", "Terry Pratchett (Night Watch) "),
    ("It's still magic even if you know how it's done.", "Terry Pratchett (A Hat Full of Sky) "),
    ("Insanity is catching.", "Terry Pratchett (Making Money) "),
    ("If you have a procedure with 10 parameters, you probably missed some.", "Alan Perlis"),
    ("Hardware : The parts of a computer system that can be kicked.", "Jeff Pesis"),
    ("The best way to accelerate a Macintosh is at 9.8 m/sec/sec.", "Marcus Dolengo"),
    ("To err is human - and to blame it on a computer is even more so.", "Robert Orben"),
    ("A computer once beat me at chess, but it was no match for me at kick boxing.", "Emo Philips"),
    ("A computer is like an Old Testament god, with a lot of rules and no mercy", "Joseph Campbell"),
    ("Technology: No Place for Wimps!", "Scott Adams"),
    ("You can no more win a war than you can win an earthquake.", "Jeanette Rankin"),
    ("All great truths begin as blasphemies.", "George Bernard Shaw"),
    ("The injury we do and the one we suffer are not weighed in the same scale.", "Aesop"),
    ("Take only memories; leave nothing but footprints.", "Chief Seattle"),
    ("They made a wasteland and called it peace.", "Tacitus"),
    ("A terrorist is someone who has a bomb but can't afford an air force.", "William Blum"),
    ("What you do speaks so loud that I cannot hear what you say.", "Ralph Waldo Emerson"),
    ("You know your god is man-made when he hates all the same people you do.", "[Usenet]"),
    ("A conservative is a man who is too cowardly to fight and too fat to run.", "Elbert Hubbard"),
    ("Religion is what keeps the poor from murdering the rich.", "Napoleon"),
    ("Never be deceived that the rich will allow you to vote away their wealth.", "Lucy Parsons"),
    ("The ink of the scholar is holier than the blood of the martyr.", "Prophet Muhammad"),
    ("Which is it, is man one of God's blunders or is God one of man's?", "Nietzsche"),
    ("Men are not punished for their sins, but by them.", "Elbert G Hubbard"),
    ("The same people that wrote the bible thought the world was flat.", "Unknown - (disputed)"),
    ("If god created us in his image we have certainly returned the compliment.", "Voltaire"),
    ("Be happy while you're living, for you're a long time dead.", "Scottish proverb"),
    ("Git yer guns, the liberal folks are gonna let the coloreds vote!", "Unknown"),
    ("The people who have really made history are the martyrs.", "Aleister Crowley"),
    ("Men who believe absurdities will commit atrocities.", "Voltaire"),
    ("Knowledge, idea, belief stands in the way of wisdom.", "J. Krishnamurthi"),
    ("We choose our joys and sorrows long before we experience them.", "Kahlil Gibran"),
    ("Statistically one hundred percent of the shots you don't take don't go in.", "Wayne Gretsky"),
    ("God favors no group. Only religions do that.", "Bumper Sticker"),
    ("On the outskirts of every agony sits some observant fellow who points.", "Virginia Woolf"),
    ("The fascist state is the corporate state.", "Benito Mussolini"),
    ("Guns make us powerful; butter will only make us fat.", "Nazi Hermann Goering"),
    ("Humanity without religion is like a serial killer without a chainsaw.", "Unknown"),
    ("Fascism is capitalism in decay.", "Vladimir Ilyich Lenin"),
    ("We need a common enemy to unite us.", "Condoleezza Rice, March 2000"),
    ("Peace is over rated. Any slave can have peace. Just pick the cotton.", "TheSong"),
    ("Pain is certain, suffering is optional.", "Buddha"),
    ("The Pope!?! How many divisions has he got?", "Joseph Stalin"),
    ("Probably no nation is rich enough to pay for both war and education.", "Braham Flexner"),
    ("Everyone laughs and cries in the same language.", "dreamslaughter"),
    ("The first clergyman was the first rascal who met the first fool.", "Voltaire"),
    ("Democracy is four wolves and a lamb voting on what to have for lunch.", "Ambrose Bierce"),
    ("No one rules if no one obeys.", "<TaoDo>"),
    ("All Bibles are man-made.", "Thomas Edison"),
    ("How good bad music and bad reasons sound when we march against an enemy!", "Nietzsche"),
    ("You get what anyone gets; you get a lifetime.", "Death, Neil Gaiman Comic Sandman"),
    ("To be wronged is nothing unless you continue to remember it.", "Confucius"),
    ("We hang the petty thieves and appoint the great ones to public office.", "Aesop"),
    ("Convictions are more dangerous foes of truth than lies.", "Nietzsche"),
    ("In matters of conscience, the law of majority has no place.", "Mohandas Gandhi"),
    ("In every country and every age, the priest has been hostile to liberty.", "Thomas Jefferson"),
    ("Like all dreamers, I mistook disenchantment for truth.", "Jean Paul Sartre"),
    ("If you speak the truth, have one foot in the stirrup.", "Turkish proverb"),
    ("To sin by silence when they should protest makes cowards of men.", "Abraham Lincoln"),
    ("Reality is that which, when you stop believing in it, doesn't go away.", "Philip K. Dick"),
    ("It is hard to free fools from chains they revere.", "Voltaire"),
    ("I don't really miss God, but I sure miss Santa Claus!", "Courtney Love"),
    ("Distrust all in whom the impulse to punish is powerful.", "Nietzsche"),
    ("The truth is more important than the facts.", "Frank Lloyd Wright"),
    ("The world is divided into people who think they are right.", "Unknown"),
    ("My opinions may have changed, but not the fact that I am right.", "Ashleigh Brilliant"),
    ("Never forget that everything Hitler did in Germany was legal.", "Martin Luther King, Jr."),
    ("Pity the warrior that kills all his foe.", "Star Trek"),
    ("Every day people are straying away from the church and going back to God.", "Lenny Bruce"),
    ("The wise man will love; all others will desire.", "Afranius"),
    ("Christianity makes suffering contagious.", "Nietzsche"),
    ("May your fondest wish be granted.", "Traditional Chinese curse"),
    ("Believe those who are seeking the truth; doubt those who find it.", "Andre Gide"),
    ("That's not a lie, it's a terminological inexactitude.", "Alexander Haig"),
    ("It is better to be feared than loved, if you cannot be both.", "Niccolo Machiavelli"),
    ("In order to learn, one must change one's mind.", "Orson Scott Card"),
    ("Every anarchist is a baffled dictator.", "Benito Mussolini"),
    ("Patriotism is the virtue of the vicious.", "Oscar Wilde"),
    ("Do not do an immoral thing for moral reasons.", "Thomas Hardy"),
    ("There must be more to life than having everything.", "Maurice Sendak"),
    ("Knowledge comes, but wisdom lingers.", "Alfred, Lord Tennyson"),
    ("I had a lover's quarrel with the world.", "Robert Frost"),
    ("Computers are useless. They can only give you answers.", "Pablo Picasso"),
    ("You simply cannot hang a millionaire in America.", "Bourke Cockran"),
    ("When the president does it that means it is not illegal.", "Richard Nixon"),
    ("Gentlemen, you can't fight in here! This is the War Room!", "Dr. Strangelove"),
    ("Your every decision conspires to make this moment happen.", "Christi Philpott"),
    ("It is your business, when the wall next door catches fire.", "Horace"),
    ("Translate 'Allah'.", "Bumper Sticker"),
    ("A conservative government is an organized hypocrisy.", "Benjamin Disraeli"),
    ("In a time of universal deceit, telling the truth is a revolutionary act.", "George Orwell"),
    ("All I know is that I am not a Marxist.", "Karl Marx"),
    ("Never was anything great achieved without danger.", "Niccolo Machiavelli"),
    ("If you understand everything, you must be misinformed.", "Japanese Proverb"),
    ("We've got to pause and ask ourselves, how much clean air do we need?", "Lee Iacocca"),
    ("I do not read advertisements. I would spend all of my time wanting things.", "Franz Kafka"),
    ("Don't join the book burners.", "Dwight D. Eisenhower"),
    ("Everything should be made as simple as possible, but not simpler.", "Albert Einstein"),
    ("We could have saved the Earth but we were too damned cheap.", "Kurt Vonnegut"),
    ("Irrationally held truths may be more harmful than reasoned errors.", "Thomas Huxley"),
    ("Religion is not merely the opium of the masses; it's the cyanide.", "Tom Robbins"),
    ("Nothing overshadows truth so much as authority.", "Leon Battista Alberti"),
    ("A language is a dialect with an army and a navy.", "Max Weinreich"),
    ("Beware of the man whose god is in the skies.", "George Bernard Shaw"),
    ("People with virtue must speak out; People who speak are not all virtuous.", "Confucius"),
    ("One death is a tragedy. A million deaths is a statistic.", "Josef Stalin"),
    ("To use the term blind faith, is to use an adjective needlessly.", "Julian Ruck"),
    ("All warfare is based on deception.", "Sun tzu"),
    ("Nothing brings people together more, than mutual hatred.", "Henry Rollins"),
    ("The best way to make children good is to make them happy.", "Oscar Wilde"),
    ("Whatever the natural cause, sin is the true cause of all earthquakes.", "John Wesley"),
    ("Anyone who has two shirts when someone has none is not a Christian.", "Lenny Bruce"),
    ("You exist only in what you do.", "Federico Fellini"),
    ("Any fool can make a rule, and any fool will mind it.", "Henry David Thoreau"),
    ("There are three truths: my truth, your truth, and the truth.", "Chinese proverb"),
    ("People only see what they are prepared to see.", "Ralph Waldo Emerson"),
    ("Lying is done with words and also with silence.", "Adrienne Rich"),
    ("The man who accumulates, whether money or knowledge, can never be free.", "J. Krishnamurthi"),
    ("I never advocated war except as a means of peace.", "Ulysses S. Grant"),
    ("Spiritual maturity is a lifelong process of replacing lies with truth.", "Kurt Bruner"),
    ("I was under medication when I made the decision to burn the tapes.", "Richard Nixon"),
    ("The public is wonderfully tolerant. It forgives everything except genius.", "Oscar Wilde"),
    ("Intellectuals solve problems; geniuses prevent them.", "Albert Einstein"),
    ("Do you love your Creator? Love your fellow beings first.", "Prophet Muhammad"),
    ("Laws are silent in time of war.", "Cicero"),
    ("Man was born free, and everywhere he is in chains.", "Rousseau"),
    ("Never go to sleep when your meat is on the fire.", "Pueblo"),
    ("You can't step twice into the same river.", "Heraclitus"),
    ("Necessity never made a good bargain.", "Ben Franklin"),
    ("This is very true; for my words are my own, and my actions are my ministers.", "Charles II"),
    ("Sometimes a scream is better than a thesis.", "Ralph Waldo Emerson"),
    ("There are very few monsters who warrant the fear we have of them.", "Andre Gide"),
    ("Whoever controls the media, the images, controls the culture.", "Allen Ginsberg"),
    ("Listen or your tongue will keep you deaf.", "Native American saying"),
    ("An empty stomach is not a good political advisor.", "Albert Einstein"),
    ("Only a fool tests the depth of the water with both feet.", "African proverb"),
    ("We live in our desires rather than in our achievements.", "George Moore"),
    ("The supreme art of war is to subdue the enemy without fighting.", "Sun tzu"),
    ("Oh, how bitter a thing is to look through another man's eye.", "William Shakespeare"),
    ("They that die by famine die by inches.", "Matthew Henry"),
    ("There is no sport in hate when all the rage is on one side.", "Percy B. Shelley"),
    ("Everywhere is walking distance if you have the time.", "Steven Wright"),
    ("You must ask your neighbor if you shall live in peace.", "John Clark"),
    ("It is true that liberty, so precious, must be rationed.", "Nikolai Lenin"),
    ("I refuse to be labeled immoral merely because I am godless.", "Peter Walker"),
    ("Know thy enemy and know thy self and you will win a hundred battles.", "Sun tzu"),
    ("Silence is one of the hardest arguments to refute.", "Josh Billings"),
    ("You can't wake a person who is pretending to be asleep.", "Native Proverb"),
    ("I have often regretted my speech, never my silence.", "Xenocrates"),
    ("Never does nature say one thing and wisdom another.", "Juvenal"),
    ("The quickest way of ending a war is to lose it.", "George Orwell"),
    ("Nothing unites the English like war. Nothing divides them like Picasso.", "Hugh Mills"),
    ("...as hollow as the o in god...", "Marilyn Manson"),
    ("The more you own, the more it owns you.", "Henry Rollins"),
    ("Money often costs too much.", "Ralph Waldo Emerson"),
    ("We are condemned to kill time: thus we die bit by bit.", "Octavio Paz"),
    ("Do not seek to follow in the footsteps of the wise. Seek what they sought.", "Basho"),
    ("By trying we can easily learn to endure adversity; another man's, I mean.", "Mark Twain"),
    ("Give to every other human being every right you claim for yourself.", "Robert G. Ingersoll"),
    ("Ignorance is always afraid of change.", "Jawaharlal Nehru"),
    ("Before we blame, we should first see if we can excuse.", "G. C. Lichtenberg"),
    ("Don't speak unless you can improve on the silence.", "Spanish proverb"),
    ("I would have made a good pope.", "Richard Nixon"),
    ("In politics, stupidity is not a handicap.", "Napoleon"),
    ("The purpose of law is to prevent the strong from always having their way.", "Ovid"),
    ("Time is a great teacher, but unfortunately it kills all its pupils.", "Hector Berlioz"),
    ("A man who is afraid will do anything.", "Jawaharlal Nehru"),
    ("Heresy is a cradle; orthodoxy a coffin.", "Robert G. Ingersoll"),
    ("Each of us is confined to a world of our own making.", "Shawn Mikula"),
    ("No one has ever had an idea in a dress suit.", "Sir Frederick G. Banting"),
    ("Strange is our situation here upon Earth.", "Albert Einstein"),
    ("Opportunities multiply as they are seized.", "Sun tzu"),
    ("Real knowledge is to know the extent of one's ignorance.", "Confucius"),
    ("Beliefs are what divide people. Doubt unites them.", "Peter Ustinov"),
    ("Wisdom is knowing what to do next. Virtue is doing it.", "David Starr Jordan"),
    ("You can't have everything. Where would you put it?", "Steven Wright"),
    ("You can pretend to be serious; you can't pretend to be witty.", "Sacha Guitry"),
    ("Nature does not hurry, yet everything is accomplished.", "Lao tzu"),
    ("The illegal we do immediately. The unconstitutional takes a bit longer.", "Henry Kissinger"),
    ("The victor will never be asked if he told the truth.", "Adolf Hitler"),
    ("What sane person could live in this world and not be crazy?", "Ursula K. LeGuin"),
    ("Never express yourself more clearly than you think.", "Neils Bohr"),
    ("Most people drive thru life with the parking brake on.", "Lance Bradley"),
    ("The death of dogma is the birth of morality.", "Immanuel Kant"),
    ("Can you sympathize with an exploding star?", "Shawn Mikula"),
    ("The revolution is a dictatorship of the exploited against the exploiters.", "Fidel Castro"),
    ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
    ("No man's knowledge here can go beyond his experience.", "John A. Locke"),
    ("Life's under no obligation to give us what we expect.", "Margaret Mitchell"),
    ("The secret of happiness is to admire without desiring.", "F. H. Bradley"),
    ("To travel is to discover that everyone is wrong about other countries.", "Aldous Huxley"),
    ("The greatest deception men suffer is from their own opinions.", "Leonardo da Vinci"),
    ("Every man is guilty of all the good he didn't do.", "Voltaire"),
    ("Time wounds all heels.", "Jane Ace"),
    ("Beware of all enterprises that require new clothes.", "Henry David Thoreau"),
    ("Manifest plainness, embrace simplicity, reduce selfishness, have few desires.", "Lao tzu"),
    ("A man's character is his fate.", "Heraclitus"),
    ("Quarrels would not last long if only one side was wrong.", "Francois Duc de la Rochefoucauld"),
    ("Philosophers have merely interpreted the world. The point is to change it.", "Karl Marx"),
    ("I am not a communist and neither is the revolutionary movement.", "Fidel Castro"),
    ("Science is the great antidote to the poison of enthusiasm and superstition.", "Adam Smith"),
    ("Once all struggle is grasped, miracles are possible.", "Mao Tse Tung"),
    ("We will be known by the tracks we leave behind.", "Dakota proverb"),
    ("Never interrupt your enemy when he is making a mistake.", "Napoleon"),
    ("When the water starts boiling it is foolish to turn off the heat.", "Nelson Mandela"),
    ("Try not to become a man of success but rather to become a man of value.", "Albert Einstein"),
    ("If I can't dance, I don't want to be part of your revolution.", "Emma Goldman"),
    ("It is not what we do, but also what we do not do, for which we are accountable.", "Moliere"),
    ("Religion is excellent stuff for keeping common people quiet.", "Napoleon"),
    ("Living is change; Growth is optional.", "Juan Wa Chang"),
    ("You have not converted a man because you have silenced him.", "John Morley"),
    ("The hardest years in life are those between ten and seventy.", "Helen Hayes, age 83"),
    ("Everything has been figured out, except how to live.", "Jean Paul Sartre"),
    ("The vast majority of mankind is trapped within perceptual prisons.", "Shawn Mikula"),
    ("Write injuries in sand, kindnesses in marble.", "French proverb"),
    ("It is not impossible to govern Italians. It is merely useless.", "Benito Mussolini"),
    ("Always remember you are a totally unique individual; just like everyone else.", "Unknown"),
    ("Mythology is what we call someone else's religion.", "Joseph Campbell"),
    ("Christian is a VERB not a noun.", "Meria Heller"),
    ("Beware the man of one book.", "Saint Thomas Aquinas"),
    ("Nothing exists except atoms and empty space; everything else is opinion.", "Democritus"),
    ("The believer is happy; the doubter is wise.", "Hungarian Proverb"),
    ("I complained that I had no shoes until I met a man who had no feet.", "Persian proverb"),
    ("Genius may have its limitations, but stupidity is not thus handicapped.", "Elbert Hubbard"),
    ("Asswhole = a complete ass", "John McTaggart in bpot"),
    ("I have seen the future and it is just like the present, only longer.", "Albran"),
    ("Smoking is one of the leading causes of statistics.", "Fletcher Knebel"),
    ("Talk sense to a fool and he calls you foolish.", "Euripides"),
    ("Invading Iraq after 9/11 was like invading Mexico after Pearl Harbor.", "Richard Clarke"),
    ("Ignorance simplifies ANY problem.", "R. Lucke"),
    ("After every 'victory' you have more enemies.", "Jeanette Winterson"),
    ("Our children are not born to hate, they are raised to hate.", "Thomas della Peruta"),
    ("Guard against the impostures of pretended patriotism.", "George Washington"),
    ("The worst crimes were dared by a few, willed by more and tolerated by all.", "Tacitus"),
    ("War is fear cloaked in courage.", "General William Westmoreland"),
    ("It is far easier to make war than peace.", "Georges Clemenceau"),
    ("War doesn't make boys men, it makes men dead.", "Ken Gillespie"),
    ("It is the job of thinking people not to be on the side of the executioners.", "Albert Camus"),
    ("Peace is constructed, not fought for.", "Brent Davis"),
    ("It is dangerous to be right when the government is wrong.", "Voltaire"),
    ("Everything secret degenerates, even the administration of justice.", "Lord Acton"),
    ("Military justice is to justice what military music is to music.", "Groucho Marx"),
    ("Violence is the last refuge of the incompetent.", "Issac Asimov"),
    ("A state of war only serves as an excuse for domestic tyranny.", "Aleksandr Solzhenitsyn"),
    ("To jaw-jaw is always better than to war-war.", "Winston Churchill"),
    ("It's wonderful to be here in the great state of Chicago.", "Dan Quayle"),
    ("If Al Gore invented the Internet, I invented spell check.", "Dan Quayle "),
    ("The company doesn't tell me what to say, and I don't tell them where to stick it.", "Unknown"),
    ("The only way to combat criminals is by not voting for them.", "Dayton Allen"),
    ("A camel is a horse designed by a committee", "Unknown"),
    ("Sex is like air. It's only a big deal if you can't get any.", "Unknown"),
    ("The bureaucracy is expanding to meet the needs of an expanding bureaucracy.", "Unknown"),
    ("Jesus may love you, but I think you're garbage wrapped in skin.", "Michael O'Donohugh"),
    ("The study of non-linear physics is like the study of non-elephant biology.", "Unknown"),
    ("I do not have a body, I am a body.", "Unknown"),
    ("A radioactive cat has eighteen half-lives.", "Unknown"),
    ("Clothes make the man. Naked people have little or no influence on society.", "Mark Twain"),
    ("I doubt, therefore I might be.", "Unknown"),
    ("If you believe in telekinesis, raise my hand.", "Unknown"),
    ("I have spoken many a word, therefore, it is fact.", "Eric the Verbose"),
    ("Puritanism: The haunting fear that someone, somewhere, may be happy.", "H. L. Mencken"),
    ("A terrorist is someone who has a bomb, but doesn't have an air force.", "William Blum"),
    ("You cannot depend on your eyes when your imagination is out of focus.", "Mark Twain"),
    ("Once you've written TBicycle, you never forget how.", "Oliver Townshend in b.p.d.n-t. "),
    ("When the rich think about the poor, they have poor ideas.", "Evita Peron "),
    ("Any fool can criticize, condemn, and complain - and most fools do.", "Dale Carnegie"),
    ("If you can read this you're not aiming in the right direction.", "Toilet-ceiling graffiti"),
    ("I hope life isn't a big joke ... because I don't get it.", "Unknown"),
    ("I'd stop eating chocolate, but I'm no quitter.", "Unknown"),
    ("I'm so poor I can't even pay attention.", "Unknown"),
    ("A physicist is an atom's way of knowing about atoms.", "George Wald"),
    ("It's the liberal bias. The press is liberally biased to the right.", "Ken de Camargo"),
    ("Humor is by far the most significant activity of the human brain.", "Edward De Bono"),
    ("One doesn't have a sense of humor. It has you.", "Larry Gelbart"),
    ("Humor is just another defense against the universe.", "Mel Brooks (1926- )"),
    ("Comedy is simply a funny way of being serious.", " Peter Ustinov (1921-2004)"),
    ("Comedy is nothing more than tragedy deferred.", "Pico Iyer, Time"),
    ("Wit makes its own welcome and levels all distinctions.", "Ralph Waldo Emerson (1803-1882)"),
    ("Humor is also a way of saying something serious.", "T. S. Eliot (1888 - 1965)"),
    ("Small minds run in the same gutter.", "Alfred E. Neuman"),
    ("Computer dating is fine, if you're a computer.", "Rita May Brown."),
    ("To err is human, but to really foul things up you need a computer.", "Paul Ehrlich."),
    ("Beware of computer programmers that carry screwdrivers.", "Leonard Brandwein."),
    ("Not even computers will replace committees, because committees buy computers.", "Unknown"),
    ("I do not fear computers. I fear the lack of them.", "Isaac Asimov."),
    ("Only one man ever understood me, and he didn't understand me.", "GW Hegel."),
    ("The secret of creativity is knowing how to hide your sources.", "Albert Einstein."),
    ("When I die I'm going to leave my body to science fiction.", "Steven Wright."),
    ("If there is no God, who pops up the next Kleenex?", "Art Hoppe."),
    ("Not only is there no God, but you try getting a plumber at weekends.", "Woody Allen."),
    ("As God once said, and I think rightly...", "Margaret Thatcher."),
    ("Hearing nuns' confessions is like being stoned to death with popcorn.", "Fulton Sheen."),
    ("Thank God I'm an atheist.", "Luis Bunuel."),
    ("If absolute power corrupts absolutely, where does that leave God?", "George Deacon."),
    ("I would have made a good Pope.", "Richard Nixon."),
    ("God is love, but get it in writing.", "Gypsy Rose Lee."),
    ("I don't pray because I don't want to bore God.", "Orson Welles."),
    ("I have four children which is not bad considering I'm not a Catholic.", "Peter Ustinov."),
    ("I hear Glenn Hoddle has found God. That must have been one hell of a pass.", "Bob Davies."),
    ("There is a charm about the forbidden that makes it unspeakably diserable.", "Mark Twain."),
    ("Always go to other people's funerals, otherwise they won't come to yours.", "Yogi Berra."),
    ("Death is a low chemical trick played on everybody except sequoia trees.", "JJ Furnas."),
    ("Early to rise and early to bed. Makes a male healthy, wealthy and dead.", "James Thurber."),
    ("Everybody wants to go to heaven, but nobody wants to die.", "Joe Louis."),
    ("He had decided to live forever or die in the attempt.", "Joseph Heller."),
    ("A single death is a tragedy, a million deaths is a statistic.", "Joseph Stalin."),
    ("Eternal nothingness is fine if you happen to be dressed for it.", "Woody Allen."),
    ("In this world, nothing is certain but death and taxes.", "Benjamin Franklin."),
    ("For if he like a madman lived, At least he like a wise one died.", "Cervantes."),
    ("Am I lightheaded because I'm not dead or because I'm still alive?", "Heidi Sandige."),
    ("A low voter turnout is an indication of fewer people going to the polls.", "George W. Bush"),
    ("Rarely is the question asked: Is our children learning?", "George W. Bush"),
    ("It's clearly a budget. It's got a lot of numbers in it.", "George W. Bush"),
    ("The most important job is not to be Governor, or First Lady in my case.", "George W. Bush"),
    ("You'll notice that Nancy Reagan never drinks water when Ronnie speaks.", "Robin Williams."),
    ("Behind every successful man is a woman, behind her is his wife.", "Groucho Marx"),
    ("Marry me and I'll never look at another horse!", "Groucho Marx"),
    ("A woman is an occasional pleasure but a cigar is always a smoke.", "Groucho Marx"),
    ("Women should be obscene and not heard.", "Groucho Marx"),
    ("Either he's dead or my watch has stopped.", "Groucho Marx"),
    ("I don't care to belong to a club that accepts people like me as members.", "Groucho Marx"),
    ("I must confess, I was born at a very early age.", "Groucho Marx"),
    ("I have had a perfectly wonderful evening, but this wasn't it.", "Groucho Marx"),
    ("Room service? Send up a larger room.", "Groucho Marx"),
    ("I never forget a face, but in your case I'll be glad to make an exception.", "Groucho Marx"),
    ("A man's only as old as the woman he feels.", "Groucho Marx"),
    ("If I held you any closer I would be on the other side of you.", "Groucho Marx"),
    ("I was married by a judge. I should have asked for a jury.", "Groucho Marx"),
    ("Who are you going to believe, me or your own eyes?", "Groucho Marx"),
    ("Quote me as saying I was mis-quoted.", "Groucho Marx"),
    ("A child of five could understand this. Fetch me a child of five.", "Groucho Marx"),
    ("Those are my principles. If you don't like them I have others.", "Groucho Marx"),
    ("I failed to make the chess team because of my height.", "Woody Allen"),
    ("The pen is mightier than the sword, and considerably easier to write with.", "Marty Feldman."),
    ("I'm desperately trying to figure out why kamikaze pilots wore helmets.", "Dave Edison."),
    ("A sure cure for seasickness is to sit under a tree.", "Spike Milligan."),
    ("Why don't they make the whole plane out of that black box stuff.", "Steven Wright."),
    ("You're about as useful as a one-legged man at an arse kicking contest.", "Rowan Atkinson."),
    ("Reality is that which, when you stop believing in it, doesn't go away.", "Philip K. Dick."),
    ("Write a wise word and your name will live forever.", "Anonymous"),
    ("Minsky's Second Law: Don't just do something. Stand there.", "Marvin Minsky"),
    ("Lohr's Law: The future is merely the past with a twist - and better tools.", "Steve Lohr"),
    ("Anyone who starts a sentence, 'With all due respect ...' is about to insult you.", "unknown"),
    ("We are Dyslexia of Borg. Fusistance is retile. Your ass will be laminated.", "unknown"),
    ("I don't approve of political jokes... I've seen too many of them get elected.", "unknown"),
    ("I plan to live forever. So far so good.", "Rob C. Claffie in borland.public.off-topic"),
    ("When you hear hoofbeats, think of horses, not zebras.", "Old saying"),
    ("1001 words say more than one picture", "Chinese proverb"),
    ("The purpose of computing is not numbers but insight.", "Richard Hamming"),
    ("Absence of evidence is not evidence of absence.", "Source Unknown"),
    ("Reality is merely an illusion, albeit a very persistent one.", "Albert Einstein "),
    ("Testing proves the presence, not the absence, of bugs.", "Edsger Dijkstra"),
    ("A model is done when nothing else can be taken out.", "Dyson "),
    ("Java, the best argument for Smalltalk since C++.", "unknown"),
    ("Computers are useless; they can only give you answers.", "Pablo Picasso "),
    ("Life would be so much easier if we could just see the source code.", "unknown"),
    ("Deliver yesterday, code today, think tomorrow.", "unknown"),
    ("C++: an octopus made by nailing extra legs onto a dog", "unknown "),
    ("God is real unless declared integer", "david "),
    ("Java: the elegant simplicity of C++ and the blazing speed of Smalltalk.", "Roland Turner"),
    ("Quotation confesses inferiority.", "Ralph Waldo Emerson "),
    ("Sometimes, the best answer is a more interesting question", "Terry Pratchett "),
    ("Before C++ we had to code all of our bugs by hand; now we inherit them.", "unknown "),
    ("Incrementing C by 1 is not enough to make a good object-oriented language.", "M. Sakkinen"),
    ("Computer /nm./: a device designed to speed and automate errors.", "From the Jargon File. "),
    ("RAM /abr./: Rarely Adequate Memory.", "From the Jargon File"),
    ("2 + 2 = 5, for extremely large values of 2.", "unknown"),
    ("ASCII stupid question, get a stupid ANSI !", "unknown"),
    ("Multitasking /adj./ 3 PCs and a chair with wheels !", "unknown"),
    ("If it wasn't for C, we'd be writing programs in BASI, PASAL, and OBOL.", "unknown"),
    ("A hen is only an egg's way of making another egg.", "Samuel Butler"),
    ("It is a miracle that curiosity survives formal education.", "Albert Einstein"),
    ("Gravity cannot be held responsible for people falling in love.", "Albert Einstein"),
    ("Common sense is the collection of prejudices acquired by age eighteen.", "Albert Einstein"),
    ("The secret to creativity is knowing how to hide your sources.", "Albert Einstein"),
    ("Intellectuals solve problems; geniuses prevent them.", "Albert Einstein"),
    ("To iterate is human, to recurse divine.", "L. Peter Deutsch"),
    ("Premature optimization is the root of all evil.", "Donald Knuth"),
    ("UNIX is simple. It just takes a genius to understand its simplicity.", "Dennis Ritchie"),
    ("I'd give my right arm to be ambidextrous.", "Brian Kernighan"),
    ("Yes, I'm fat, but you're ugly and I can go on a diet.", "bumper sticker"),
    ("Time is the best teacher; Unfortunately it kills all its students!", "bumper sticker"),
    ("Ever stop to think, and forget to start again?", "bumper sticker"),
    ("If quantum physics doesn't confuse you then you don't understand it.", "Niels Bohr "),
    ("Moral indignation is jealousy with a halo.", "H. G. Wells (1866-1946)"),
    ("Glory is fleeting, but obscurity is forever.", "Napoleon Bonaparte (1769-1821)"),
    ("Don't be so humble - you are not that great.", "Golda Meir (1898-1978) to a visiting diplomat"),
    ("His ignorance is encyclopedic", "Abba Eban (1915-2002)"),
    ("If a man does his best, what else is there?", "General George S. Patton (1885-1945)"),
    ("Give me chastity and continence, but not yet.", "Saint Augustine (354-430)"),
    ("This book fills a much-needed gap.", "Moses Hadas (1900-1966) in a review"),
    ("Give me a museum and I'll fill it.", "Pablo Picasso (1881-1973)"),
    ("Assassins!", "Arturo Toscanini (1867-1957) to his orchestra"),
    ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson (1743-1826)"),
    ("Do, or do not. There is no 'try'.", "Yoda ('The Empire Strikes Back')"),
    ("The only way to get rid of a temptation is to yield to it.", "Oscar Wilde (1854-1900)"),
    ("Don't stay in bed, unless you can make money in bed.", "George Burns (1896-1996)"),
    ("A mathematician is a device for turning coffee into theorems.", "Paul Erdos"),
    ("Some cause happiness wherever they go; others, whenever they go.", "Oscar Wilde (1854-1900)"),
    ("God is a comedian playing to an audience too afraid to laugh.", "Voltaire (1694-1778)"),
    ("I shall not waste my days in trying to prolong them.", "Ian L. Fleming (1908-1964)"),
    ("If you can count your money, you don't have a billion dollars.", "J. Paul Getty (1892-1976)"),
    ("Maybe this world is another planet's Hell.", "Aldous Huxley (1894-1963)"),
    ("I've had a wonderful time, but this wasn't it.", "Groucho Marx (1895-1977)"),
    ("Be nice to people on your way up because you meet them on your way down.", "Jimmy Durante"),
    ("To love oneself is the beginning of a lifelong romance", "Oscar Wilde (1854-1900)"),
    ("Knowledge speaks, but wisdom listens.", "Jimi Hendrix"),
    ("A clever man commits no minor blunders.", "Goethe (1749-1832)"),
    ("Argue for your limitations, and sure enough they're yours.", "Richard Bach"),
    ("A witty saying proves nothing.", "Voltaire (1694-1778)"),
    ("Education is a progressive discovery of our own ignorance.", "Will Durant"),
    ("I have often regretted my speech, never my silence.", "Xenocrates (396-314 B.C.)"),
    ("If everything seems under control, you're just not going fast enough.", "Mario Andretti"),
    ("I'll sleep when I'm dead.", "Warren Zevon"),
    ("While we are postponing, life speeds by.", "Seneca (3BC - 65AD)"),
    ("Where are we going, and why am I in this handbasket?", "Bumper Sticker"),
    ("God, please save me from your followers!", "Bumper Sticker"),
    ("Wit is educated insolence.", "Aristotle (384-322 B.C.)"),
    ("Egotist: a person more interested in himself than in me.", "Ambrose Bierce (1842-1914)"),
    ("We all agree that your theory is crazy, but is it crazy enough?", "Niels Bohr (1885-1962)"),
    ("I would have made a good Pope.", "Richard M. Nixon (1913-1994)"),
    ("In any contest between power and patience, bet on patience.", "W.B. Prescott"),
    ("It is unbecoming for young men to utter maxims.", "Aristotle (384-322 B.C.)"),
    ("Reality is merely an illusion, albeit a very persistent one.", "Albert Einstein (1879-1955)"),
    ("A little inaccuracy sometimes saves a ton of explanation.", "H. H. Munro (Saki) (1870-1916)"),
    ("Make everything as simple as possible, but not simpler.", "Albert Einstein (1879-1955)"),
    ("A man can't be too careful in the choice of his enemies.", "Oscar Wilde (1854-1900)"),
    ("Forgive your enemies, but never forget their names.", "John F. Kennedy (1917-1963)"),
    ("Logic is in the eye of the logician.", "Gloria Steinem"),
    ("No one can earn a million dollars honestly.", "William Jennings Bryan (1860-1925)"),
    ("Everything has been figured out, except how to live.", "Jean-Paul Sartre (1905-1980)"),
    ("It is better to have a permanent income than to be fascinating.", "Oscar Wilde (1854-1900)"),
    ("When ideas fail, words come in very handy.", "Goethe (1749-1832)"),
    ("In the end, everything is a gag.", "Charlie Chaplin (1889-1977)"),
    ("I love Mickey Mouse more than any woman I have ever known.", "Walt Disney (1901-1966)"),
    ("He who hesitates is a damned fool.", "Mae West (1892-1980)"),
    ("Good teaching is one-fourth preparation and three-fourths theater.", "Gail Godwin"),
    ("The graveyards are full of indispensable men.", "Charles de Gaulle (1890-1970)"),
    ("You can pretend to be serious; you can't pretend to be witty.", "Sacha Guitry (1885-1957)"),
    ("Behind every great fortune there is a crime.", "Honore de Balzac (1799-1850)"),
    ("I am not young enough to know everything.", "Oscar Wilde (1854-1900)"),
    ("Sometimes a scream is better than a thesis.", "Ralph Waldo Emerson (1803-1882)"),
    ("There is no sincerer love than the love of food.", "George Bernard Shaw (1856-1950)"),
    ("I don't even butter my bread; I consider that cooking.", "Katherine Cebrian"),
    ("I have an existential map; it has 'you are here' written all over it.", "Steven Wright"),
    ("I have read your book and much like it.", "Moses Hadas (1900-1966)"),
    ("The covers of this book are too far apart.", "Ambrose Bierce (1842-1914)"),
    ("Too many pieces of music finish too long after the end.", "Igor Stravinsky (1882-1971)"),
    ("Anything that is too stupid to be spoken is sung.", "Voltaire (1694-1778)"),
    ("No Sane man will dance.", "Cicero (106-43 B.C.)"),
    ("Hell is a half-filled auditorium.", "Robert Frost (1874-1963)"),
    ("Show me a sane man and I will cure him for you.", "Carl Gustav Jung (1875-1961)"),
    ("Vote early and vote often.", "Al Capone (1899-1947)"),
    ("If I were two-faced, would I be wearing this one?", "Abraham Lincoln (1809-1865)"),
    ("Hell is other people.", "Jean-Paul Sartre (1905-1980)"),
    ("Happiness is good health and a bad memory.", "Ingrid Bergman (1917-1982)"),
    ("Friends may come and go, but enemies accumulate.", "Thomas Jones"),
    ("The gods too are fond of a joke.", "Aristotle (384-322 B.C.)"),
    ("Distrust any enterprise that requires new clothes.", "Henry David Thoreau (1817-1862)"),
    ("The difference between pornography and erotica is lighting.", "Gloria Leonard"),
    ("The cynics are right nine times out of ten.", "Henry Louis Mencken (1880-1956)"),
    ("Attention to health is life's greatest hindrance.", "Plato (427-347 B.C.)"),
    ("Plato was a bore.", "Friedrich Nietzsche (1844-1900)"),
    ("Nietzsche was stupid and abnormal.", "Leo Tolstoy (1828-1910)"),
    ("I'm not going to get into the ring with Tolstoy.", "Ernest Hemingway (1899-1961)"),
    ("Hemingway was a jerk.", "Harold Robbins "),
    ("How can I lose to such an idiot?", "A shout from chessmaster Aaron Nimzovich (1886-1935)"),
    ("I don't feel good.", "The last words of Luther Burbank (1849-1926)"),
    ("Men have become the tools of their tools.", "Henry David Thoreau (1817-1862)"),
    ("I have never let my schooling interfere with my education.", "Mark Twain (1835-1910)"),
    ("I never miss a chance to have sex or appear on television.", "Gore Vidal"),
    ("To sit alone with my conscience will be judgment enough for me.", "Charles William Stubbs"),
    ("Sanity is a madness put to good uses.", "George Santayana (1863-1952)"),
    ("Imitation is the sincerest form of television.", "Fred Allen (1894-1956)"),
    ("Always do right- this will gratify some and astonish the rest.", "Mark Twain (1835-1910)"),
    ("Copy from one, it's plagiarism; copy from two, it's research.", "Wilson Mizner (1876-1933)"),
    ("Why don't you write books people can read?", "Nora Joyce to her husband James (1882-1941)"),
    ("Some editors are failed writers, but so are most writers.", "T. S. Eliot (1888-1965)"),
    ("Criticism is prejudice made plausible.", "Henry Louis Mencken (1880-1956)"),
    ("It is better to be quotable than to be honest.", "Tom Stoppard"),
    ("Being on the tightrope is living; everything else is waiting.", "Karl Wallenda"),
    ("Opportunities multiply as they are seized.", "Sun Tzu"),
    ("The best way to predict the future is to invent it.", "Alan Kay"),
    ("Never mistake motion for action.", "Ernest Hemingway (1899-1961)"),
    ("Hell is paved with good samaritans.", "William M. Holden"),
    ("Well done is better than well said.", "Benjamin Franklin (1706-1790)"),
    ("The average person thinks he isn't.", "Father Larry Lorenzoni"),
    ("Learning is what most adults will do for a living in the 21st century.", "Perelman"),
    ("There is a country in Europe where multiple-choice tests are illegal.", "Sigfried Hulzer"),
    ("The backbone of surprise is fusing speed with secrecy.", "Von Clausewitz (1780-1831)"),
    ("640K ought to be enough for anybody.", "Bill Gates (1955-), in 1981"),
    ("Denial ain't just a river in Egypt.", "Mark Twain (1835-1910)"),
    ("A pint of sweat, saves a gallon of blood.", "General George S. Patton (1885-1945)"),
    ("The difference between fiction and reality? Fiction has to make sense.", "Tom Clancy"),
    ("Whatever is begun in anger ends in shame.", "Benjamin Franklin (1706-1790)"),
    ("Half this game is ninety percent mental.", "Yogi Berra"),
    ("I criticize by creation - not by finding fault.", "Cicero (106-43 B.C.)"),
    ("Love is friendship set on fire.", "Jeremy Taylor"),
    ("Woman was God's second mistake.", "Friedrich Nietzsche (1844-1900)"),
    ("He would make a lovely corpse.", "Charles Dickens (1812-1870)"),
    ("I've just learned about his illness. Let's hope it's nothing trivial.", "Irvin S. Cobb"),
    ("I worship the quicksand he walks in.", "Art Buchwald"),
    ("Wagner's music is better than it sounds.", "Mark Twain (1835-1910)"),
    ("A poem is never finished, only abandoned.", "Paul Valery (1871-1945)"),
    ("The truth is more important than the facts.", "Frank Lloyd Wright (1868-1959)"),
    ("A coward is a hero with a wife, kids, and a mortgage.", "Marvin Kitman."),
    ("I'm not into working out. My philosophy: No pain, no pain.", "Carol Leifer."),
    ("Now comes the mystery", "Henry Ward Beecher, dying words, March 8, 1887"),
    ("I don't feel good.", "Luther Burbank, dying words"),
    ("The nourishment is palatable", "Emily Dickinson, dying words"),
    ("They couldn't hit an elephant at this dist--", "John B. Sedwick, general, dying words, 1864"),
    ("I still live.", "Daniel Webster, dying words"),
    ("Go away...I'm alright.", "H.G.Wells, dying words"),
    ("Friends applaud, the Comedy is over.", "Ludwig von Beethoven, dying words"),
    ("Ah well, then I suppose I shall have to die beyond my means.", "Oscar Wilde, dying words"),
    ("Never raise your hands to your kids. It leaves your groin unprotected.", "Red Button"),
    ("I'm in shape. Round is a shape.", "George Carlin"),
    ("Do illiterate people get the full effect of alphabet soup?", "John Mendoza"),
    ("I've always wanted to be somebody, but I should have been more specific.", "George Carlin"),
    ("Benny Goodman plays the clarinet. I play music.", "Artie Shaw"),
    ("He had delusions of adequacy.", "Walter Kerr"),
    ("He has all the virtues I dislike and none of the vices I admire.", "Winston Churchill"),
    ("A modest little person, with much to be modest about.", "Winston Churchill"),
    ("Thank you for sending me a copy of your book; I'll waste no time reading it.", "Moses Hadas"),
    ("He can compress the most words into the smallest idea of any man I know.", "Abraham Lincoln"),
    ("He has no enemies, but is intensely disliked by his friends.", "Oscar Wilde"),
    ("I feel so miserable without you; it's almost like having you here.", "Stephen Bishop"),
    ("He is a self-made man and worships his creator.", "John Bright"),
    ("I've just learned about his illness. Let's hope it's nothing trivial.", "Irvin S. Cobb"),
    ("He is not only dull himself, he is the cause of dullness in others.", "Samuel Johnson"),
    ("He is simply a shiver looking for a spine to run up.", "Paul Keating"),
    ("There's nothing wrong with you that reincarnation won't cure.", "Jack E. Leonard"),
    ("He has the attention span of a lightning bolt.", "Robert Redford"),
    ("He loves nature in spite of what it did to him.", "Forrest Tucker"),
    ("Why do you sit there looking like an envelope without any address on it?", "Mark Twain"),
    ("His mother should have thrown him away and kept the stork.", "Mae West"),
    ("Some cause happiness wherever they go; others, whenever they go.", "Oscar Wilde"),
    ("He has Van Gogh's ear for music.", "Billy Wilder"),
    ("I liked your opera. I think I will set it to music.", "Beethoven to a fellow composer"),
    ("That's not writing; That's typing.", "Truman Capote on Jack Kerouac"),
    ("If I'd listened to customers, I'd have given them a faster horse.", "Henry Ford"),
    ("The first principle is that you must not fool yourself, and you are the easiest person to fool.", "Richard P. Feynman"),
]

